[package]
name = "wgpu_context"
description = "Context for managing WGPU surfaces"
version = "0.3.1"
documentation = "https://docs.rs/wgpu_context"
license.workspace = true
edition.workspace = true

[dependencies]
wgpu = { workspace = true }
futures-intrusive = { workspace = true }
